### ISSUE TITLE
Hello there ?

### ISSUE THREAD

**Issue by wmcmurray** [nwbb/node-brightcove#4]
Considering that the last commit on this project is **3 years old** and that there is absolutely **no activities displayed on your profile** (for a period of one year), may I ask you if this repo is still active ? If I want to do some pull-request to improve it, will you merge them or should I code my own stuff outside this project ?

Thank you :)

**Comment by hstonge** [comment]
The cake is a lie.

**Comment by nwbb** [comment]
Heya - yep, go for it, I'll review it and merge it in.   I know, it hasn't been actively maintained.  Not a lot of interest out there nor have I had any need to make any changes. :(

**Comment by wmcmurray** [comment]
Awesome, we will probably have to use the playback API on a project very soon so it'll add some cool stuff in here ! ...stuff almost no one will use lol

**Comment by bdeitte** [comment]
Some of us at Brightcove do watch this repo and are happy to recommend it to others... so a few people will use it.  :)

**Comment by wmcmurray** [comment]
Ahaha unexpectedly nice !

**Comment by nwbb** [comment]
That is nice, thanks!  Feel free to pass it along.

**Comment by wmcmurray** [comment]
Hi @bdeitte , I am implementing OAuth + Privacy APIs and I would like to publish some unit tests in this repo. Is there a way I can have access to a test account I could use ? I've found this in Brightcove documentation :
```
clientId : 9309bb5d-90fb-4d3a-aba4-1795dd5fa0b8
clientSecret: HHxp9xn0yxMqktLEG2DhzjYB4g6AN2cl02KudMvfK-3dT6JRtiR1tUZ7LiwtHI5vqo4VT7LuD6tM4c0llEw2Rw
```

Which seams to work but I don't have the `account_id` so I'm stuck at the "Create a Policy Key" API.

Also, I sometimes find inconsistencies between the doc and API output (variables containing underscores in doc but hyphen in API output), is there way I could report these ?

Thank you :)

**Comment by bdeitte** [comment]
Adding some docs people in for reporting the doc/API output.  @rcrooks @mboles what's the best way to report doc issues, just message you?  Do you also have any ideas on the test account question?  If not, I can ask some other folks.

**Comment by mboles** [comment]
Brian-
The best thing to do is email docs@brightcove.com as that goes directly into our JIRA queue and the correct person can then claim the ticket.
-Matt


 
Matthew Boles | Learning Specialist | Brightcove Inc.
mboles@brightcove.com
p: 941.776.7674 | c: 727.808.8016

On October 27, 2015 at 10:29:39 AM, Brian Deitte (notifications@github.com) wrote:

Adding some docs people in for reporting the doc/API output. @rcrooks @mboles what's the best way to report doc issues, just message you? Do you also have any ideas on the test account question? If not, I can ask some other folks.

**Comment by bdeitte** [comment]
@mboles You just posted this on github.com.  This isn't a question on our internal github server.  Not sure if you meant for this to go out there, or if you want other people to get info to you some other way.

**Comment by mboles** [comment]
No, that is good. That email address is on the bottom of everyone of our public support docs when you click the Questions/Comments link.
-Matt


 
Matthew Boles | Learning Specialist | Brightcove Inc.
mboles@brightcove.com
p: 941.776.7674 | c: 727.808.8016

On October 27, 2015 at 11:01:40 AM, Brian Deitte (notifications@github.com) wrote:

@mboles You just posted this on github.com. This isn't a question on our internal github server. Not sure if you meant for this to go out there, or if you want other people to get info to you some other way.

**Comment by bdeitte** [comment]
@wmcmurray I see the account_id listed in that same documentation.  So let me know if that works for you.  If not, I can see what can be done here.

**Comment by wmcmurray** [comment]
@mboles Perfect, I'll write to this address !

@bdeitte If you are talking about `57838016001`, yes I've tried it but I constantly receive a `401 Unauthorized` error... I've tried my same code with an account that I own and it worked. I first thought the account id wasen't paired with the according clientId and clientSecret, but maybe there is something else that can cause this error ?

By looking further at the API output, I just saw that I receive this along with the error :
```
Bearer error="insufficient_scope",
error_description="The access token does not carry sufficient scope"
```

**Comment by bdeitte** [comment]
@wmcmurray Yeah I'm not too surprised about that.  I was more surprised that they might have released out a token like that with real permissions on it!  :)  

I don't think there's going to be a client id/secret that's ok to release for unit tests on a public page, unfortunately.  I would suggest make the id and secret vars that can be passed in.  So something like:
```
var clientId = process.env.CLIENT_ID, 
  clientSecret = process.env.CLIENT_SECRET;
```
And then note in the README that these two environment variables need to be set for the tests to run.

I'm assuming you have your own id/secret to use that you just don't want to include in the source (of course).  If you don't have this right now, let me know that as well, that's a different problem that I might be able to solve.

**Comment by wmcmurray** [comment]
@bdeitte I completely understand, releasing a full access publicly could lead to abuses. I currently have an id/secret coming from an account created with the 30 days trial so I still have some days to work with it ahah If you have a more "permanent" solution it would be great :)
